CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Destinations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Country" character varying(100) NOT NULL,
    "Description" character varying(1000),
    "ImageUrl" text,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    CONSTRAINT "PK_Destinations" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260811172021_AddDestination', '8.0.10');

COMMIT;

START TRANSACTION;

CREATE TABLE "Tours" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DestinationId" integer NOT NULL,
    "Name" character varying(150) NOT NULL,
    "Category" character varying(50) NOT NULL,
    "Description" character varying(1000),
    "Price" numeric NOT NULL,
    "Currency" character varying(10) NOT NULL,
    "DurationHours" double precision NOT NULL,
    "DefaultStartTime" interval NOT NULL,
    "Latitude" double precision,
    "Longitude" double precision,
    "Status" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Tours" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tours_Destinations_DestinationId" FOREIGN KEY ("DestinationId") REFERENCES "Destinations" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Tours_DestinationId" ON "Tours" ("DestinationId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260812163420_AddTour', '8.0.10');

COMMIT;

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Customers" (
    "Id" text NOT NULL,
    "FullName" character varying(150) NOT NULL,
    "Phone" character varying(20),
    "JoinedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "LastActiveAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Notifications" (
    "Id" uuid NOT NULL,
    "CustomerId" text NOT NULL,
    "Channel" character varying(20) NOT NULL,
    "MessageType" character varying(30) NOT NULL,
    "Content" character varying(2000) NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'Pending',
    "ReadAt" timestamp with time zone,
    "SentAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Preferences" (
    "Id" uuid NOT NULL,
    "CustomerId" text NOT NULL,
    "BudgetMin" numeric(18,2) NOT NULL,
    "BudgetMax" numeric(18,2) NOT NULL,
    "Currency" character varying(10) NOT NULL DEFAULT 'USD',
    "PreferredActivities" character varying(500),
    "DietaryNotes" character varying(500),
    "AccessibilityNotes" character varying(500),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_Preferences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Preferences_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TripRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" text NOT NULL,
    "DestinationId" integer,
    "RawRequestText" character varying(2000) NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "TravellerCount" integer NOT NULL,
    "BudgetCeiling" numeric(18,2) NOT NULL,
    "Currency" character varying(10) NOT NULL DEFAULT 'USD',
    "Status" character varying(30) NOT NULL DEFAULT 'Pending',
    "RetryCount" integer NOT NULL DEFAULT 0,
    "PlanJson" jsonb,
    "FailureReason" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_TripRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TripRequests_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TripRequests_Destinations_DestinationId" FOREIGN KEY ("DestinationId") REFERENCES "Destinations" ("Id") ON DELETE SET NULL
);

CREATE TABLE "AgentLogs" (
    "Id" uuid NOT NULL,
    "TripRequestId" integer NOT NULL,
    "AgentName" character varying(100) NOT NULL,
    "StepName" character varying(100) NOT NULL,
    "Input" character varying(4000),
    "Output" character varying(4000),
    "Status" character varying(50) NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_AgentLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AgentLogs_TripRequests_TripRequestId" FOREIGN KEY ("TripRequestId") REFERENCES "TripRequests" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AgentLogs_TripRequestId" ON "AgentLogs" ("TripRequestId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Notifications_CustomerId" ON "Notifications" ("CustomerId");

CREATE UNIQUE INDEX "IX_Preferences_CustomerId" ON "Preferences" ("CustomerId");

CREATE INDEX "IX_TripRequests_CustomerId" ON "TripRequests" ("CustomerId");

CREATE INDEX "IX_TripRequests_DestinationId" ON "TripRequests" ("DestinationId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260819145626_AddStudentATables', '8.0.10');

COMMIT;

START TRANSACTION;

CREATE TABLE "Itineraries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" text NOT NULL,
    "TripRequestId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'Draft',
    "TotalEstimatedCost" numeric(18,2) NOT NULL,
    "Currency" character varying(10) NOT NULL DEFAULT 'USD',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_Itineraries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Itineraries_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Itineraries_TripRequests_TripRequestId" FOREIGN KEY ("TripRequestId") REFERENCES "TripRequests" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ItineraryItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ItineraryId" integer NOT NULL,
    "TourId" integer NOT NULL,
    "DayNumber" integer NOT NULL,
    "SequenceOrder" integer NOT NULL,
    "StartTime" interval NOT NULL,
    "EndTime" interval NOT NULL,
    "PriceAtSelection" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_ItineraryItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ItineraryItems_Itineraries_ItineraryId" FOREIGN KEY ("ItineraryId") REFERENCES "Itineraries" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ItineraryItems_Tours_TourId" FOREIGN KEY ("TourId") REFERENCES "Tours" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Itineraries_CustomerId" ON "Itineraries" ("CustomerId");

CREATE INDEX "IX_Itineraries_TripRequestId" ON "Itineraries" ("TripRequestId");

CREATE INDEX "IX_ItineraryItems_ItineraryId" ON "ItineraryItems" ("ItineraryId");

CREATE INDEX "IX_ItineraryItems_TourId" ON "ItineraryItems" ("TourId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260819171356_AddItineraryItems', '8.0.10');

COMMIT;

START TRANSACTION;

CREATE TABLE "Hotels" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DestinationId" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Address" character varying(500),
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "StarRating" integer NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'Active',
    CONSTRAINT "PK_Hotels" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Hotels_Destinations_DestinationId" FOREIGN KEY ("DestinationId") REFERENCES "Destinations" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TransportOptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Type" character varying(20) NOT NULL,
    "Provider" character varying(150) NOT NULL,
    "RouteFrom" character varying(200) NOT NULL,
    "RouteTo" character varying(200) NOT NULL,
    "RouteFromLatitude" double precision,
    "RouteFromLongitude" double precision,
    "RouteToLatitude" double precision,
    "RouteToLongitude" double precision,
    "DepartureTime" timestamp with time zone NOT NULL,
    "ArrivalTime" timestamp with time zone NOT NULL,
    "Capacity" integer NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "Currency" character varying(10) NOT NULL DEFAULT 'USD',
    "Status" character varying(20) NOT NULL DEFAULT 'Active',
    CONSTRAINT "PK_TransportOptions" PRIMARY KEY ("Id")
);

CREATE TABLE "Rooms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HotelId" integer NOT NULL,
    "RoomType" character varying(50) NOT NULL,
    "Capacity" integer NOT NULL,
    "TotalRooms" integer NOT NULL,
    "PricePerNight" numeric(18,2) NOT NULL,
    "Currency" character varying(10) NOT NULL DEFAULT 'USD',
    CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Rooms_Hotels_HotelId" FOREIGN KEY ("HotelId") REFERENCES "Hotels" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Hotels_DestinationId" ON "Hotels" ("DestinationId");

CREATE INDEX "IX_Rooms_HotelId" ON "Rooms" ("HotelId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260822221741_AddStudentCTables', '8.0.10');

COMMIT;

START TRANSACTION;

ALTER TABLE "Customers" ADD "Role" character varying(50) NOT NULL DEFAULT '';

CREATE TABLE "Bookings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BookingReference" character varying(50) NOT NULL,
    "CustomerId" text NOT NULL,
    "ItineraryId" integer NOT NULL,
    "Status" character varying(30) NOT NULL DEFAULT 'Draft',
    "TotalCost" numeric(18,2) NOT NULL,
    "Currency" character varying(10) NOT NULL DEFAULT 'USD',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Bookings_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Bookings_Itineraries_ItineraryId" FOREIGN KEY ("ItineraryId") REFERENCES "Itineraries" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TravelAgents" (
    "Id" text NOT NULL,
    "FullName" character varying(150) NOT NULL,
    "Department" character varying(100) NOT NULL,
    "HireDate" timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_TravelAgents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TravelAgents_AspNetUsers_Id" FOREIGN KEY ("Id") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BookingItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BookingId" integer NOT NULL,
    "ItemType" character varying(20) NOT NULL,
    "TourId" integer,
    "RoomId" integer,
    "TransportOptionId" integer,
    "CheckInDate" timestamp with time zone,
    "CheckOutDate" timestamp with time zone,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_BookingItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BookingItems_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BookingItems_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_BookingItems_Tours_TourId" FOREIGN KEY ("TourId") REFERENCES "Tours" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_BookingItems_TransportOptions_TransportOptionId" FOREIGN KEY ("TransportOptionId") REFERENCES "TransportOptions" ("Id") ON DELETE SET NULL
);

CREATE TABLE "Payments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BookingId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Currency" character varying(10) NOT NULL DEFAULT 'USD',
    "Status" character varying(20) NOT NULL DEFAULT 'Pending',
    "StripeReference" character varying(100),
    "PaymentDate" timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BookingApprovals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BookingId" integer NOT NULL,
    "TravelAgentId" text NOT NULL,
    "Decision" character varying(30) NOT NULL,
    "Comment" character varying(1000) NOT NULL,
    "DecidedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_BookingApprovals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BookingApprovals_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BookingApprovals_TravelAgents_TravelAgentId" FOREIGN KEY ("TravelAgentId") REFERENCES "TravelAgents" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_BookingApprovals_BookingId" ON "BookingApprovals" ("BookingId");

CREATE INDEX "IX_BookingApprovals_TravelAgentId" ON "BookingApprovals" ("TravelAgentId");

CREATE INDEX "IX_BookingItems_BookingId" ON "BookingItems" ("BookingId");

CREATE INDEX "IX_BookingItems_RoomId" ON "BookingItems" ("RoomId");

CREATE INDEX "IX_BookingItems_TourId" ON "BookingItems" ("TourId");

CREATE INDEX "IX_BookingItems_TransportOptionId" ON "BookingItems" ("TransportOptionId");

CREATE UNIQUE INDEX "IX_Bookings_BookingReference" ON "Bookings" ("BookingReference");

CREATE INDEX "IX_Bookings_CustomerId" ON "Bookings" ("CustomerId");

CREATE INDEX "IX_Bookings_ItineraryId" ON "Bookings" ("ItineraryId");

CREATE INDEX "IX_Payments_BookingId" ON "Payments" ("BookingId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260911115503_AddStudentDTables', '8.0.10');

COMMIT;

