using System.Text;

namespace DemoTravelCatalogueImporter;

public static class ReportWriter
{
    private static readonly (string Name, string[] Stops)[] Scenarios =
    [
        ("A - Colombo -> Kandy -> Ella", ["Colombo", "Kandy", "Ella"]),
        ("B - Colombo -> Galle -> Mirissa", ["Colombo", "Galle", "Mirissa"]),
        ("C - Colombo -> Anuradhapura -> Sigiriya", ["Colombo", "Anuradhapura", "Sigiriya"]),
        ("D - Colombo -> Trincomalee -> Batticaloa", ["Colombo", "Trincomalee", "Batticaloa"]),
        ("E - Colombo -> Jaffna -> Anuradhapura", ["Colombo", "Jaffna", "Anuradhapura"]),
        ("Batticaloa -> Colombo -> Ella", ["Batticaloa", "Colombo", "Ella"])
    ];

    public static void WriteAll(
        string repositoryRoot,
        DatabaseTargetInfo target,
        CatalogueDocument document,
        CatalogueSnapshot snapshot,
        ImportPlan plan,
        bool applyRequested,
        ApplyResult? applyResult = null)
    {
        var dryRunPath = Path.Combine(repositoryRoot, "DEMO_TRAVEL_CATALOGUE_IMPORT_DRY_RUN.md");
        var finalPath = Path.Combine(repositoryRoot, "REALISTIC_DEMO_TRAVEL_DATA_IMPORT_REPORT.md");
        File.WriteAllText(dryRunPath, BuildDryRun(target, document, snapshot, plan, applyRequested, applyResult), Encoding.UTF8);
        File.WriteAllText(finalPath, BuildFinalReport(target, document, snapshot, plan, applyRequested, applyResult), Encoding.UTF8);
    }

    private static string BuildDryRun(
        DatabaseTargetInfo target,
        CatalogueDocument document,
        CatalogueSnapshot snapshot,
        ImportPlan plan,
        bool applyRequested,
        ApplyResult? applyResult)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# DEMO TRAVEL CATALOGUE IMPORT DRY RUN");
        sb.AppendLine();
        sb.AppendLine("This report was generated by the isolated importer. Default mode performs read-only database queries and never calls `SaveChanges`.");
        sb.AppendLine();
        AppendEnvironment(sb, target);
        sb.AppendLine("## Current counts");
        AppendCounts(sb, snapshot);
        sb.AppendLine();
        sb.AppendLine("## Planned operations");
        AppendPlanCounts(sb, document, plan);
        sb.AppendLine();
        sb.AppendLine("## Verification and duplicate outcomes");
        AppendIssues(sb, plan);
        sb.AppendLine();
        sb.AppendLine("## Expected counts after a successful approved apply");
        sb.AppendLine($"- Destinations: `{snapshot.Destinations.Count + plan.DestinationsToInsert.Count}`");
        sb.AppendLine($"- Hotels: `{snapshot.Hotels.Count + plan.HotelsToInsert.Count}`");
        sb.AppendLine($"- Rooms: `{snapshot.Rooms.Count + plan.RoomsToInsert.Count}`");
        sb.AppendLine($"- Tours: `{snapshot.Tours.Count + plan.ToursToInsert.Count}`");
        sb.AppendLine($"- TransportOptions: `{snapshot.TransportOptions.Count + plan.TransportToInsert.Count}`");
        sb.AppendLine();
        sb.AppendLine("## Destination coverage");
        AppendDestinationCoverage(sb, snapshot, plan);
        sb.AppendLine();
        sb.AppendLine("## Route coverage");
        AppendRouteCoverage(sb, snapshot, plan);
        sb.AppendLine();
        sb.AppendLine("## AI read-only scenarios");
        AppendScenarios(sb, snapshot, plan);
        sb.AppendLine();
        sb.AppendLine("## Apply gate");
        if (!applyRequested)
        {
            sb.AppendLine("- Mode: `DRY RUN`");
            sb.AppendLine("- Database mutation: `0` (no write flag supplied)");
        }
        else if (!target.WriteApproved)
        {
            sb.AppendLine("- Mode: `--apply requested`");
            sb.AppendLine(target.ProductionConflict
                ? "- Result: `ENVIRONMENT_CONFLICT - production/shared signal detected`"
                : "- Result: `BLOCKED - explicit environment and write approval are required`");
            sb.AppendLine("- Database mutation: `0`");
        }
        else if (applyResult is not null)
        {
            sb.AppendLine("- Mode: `--apply`");
            sb.AppendLine($"- Applied: destinations `{applyResult.DestinationsInserted}`, hotels `{applyResult.HotelsInserted}`, rooms `{applyResult.RoomsInserted}`, tours `{applyResult.ToursInserted}`, transport `{applyResult.TransportInserted}`");
            sb.AppendLine($"- Failed batches: `{applyResult.FailedBatches}`");
        }

        return sb.ToString();
    }

    private static string BuildFinalReport(
        DatabaseTargetInfo target,
        CatalogueDocument document,
        CatalogueSnapshot snapshot,
        ImportPlan plan,
        bool applyRequested,
        ApplyResult? applyResult)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# REALISTIC DEMO TRAVEL DATA IMPORT REPORT");
        sb.AppendLine();
        sb.AppendLine("## Result");
        sb.AppendLine();
        if (applyResult is not null)
        {
            sb.AppendLine(applyResult.FailedBatches == 0
                ? "**IMPORTED AND VERIFIED**"
                : "**PARTIALLY IMPORTED**");
        }
        else
        {
            sb.AppendLine(applyRequested
                ? "**BLOCKED**"
                : "**DRY RUN COMPLETE - DATABASE WRITE BLOCKED**");
        }

        sb.AppendLine();
        sb.AppendLine("No schema migration is used. Existing booking-linked catalogue rows are never updated or deleted.");
        sb.AppendLine();
        sb.AppendLine("## Environment");
        AppendEnvironment(sb, target);
        sb.AppendLine($"- Write authorized: `{(target.WriteApproved ? "YES" : "NO")}`");
        sb.AppendLine();
        sb.AppendLine("## Baseline");
        AppendCounts(sb, snapshot);
        sb.AppendLine();
        sb.AppendLine("## Verification");
        sb.AppendLine($"- Hotels researched: `{document.Hotels.Count}`");
        sb.AppendLine($"- Hotels passing import gate: `{plan.HotelsToInsert.Count}`");
        sb.AppendLine($"- Hotels skipped/blocked: `{document.Hotels.Count - plan.HotelsToInsert.Count}`");
        sb.AppendLine($"- Destinations verified for import: `{document.Destinations.Count(d => d.Verified)}` of `{document.Destinations.Count}` candidates");
        sb.AppendLine($"- Tours researched: `{document.Tours.Count}`");
        sb.AppendLine($"- Tours passing destination/identity gate: `{plan.ToursToInsert.Count}`");
        sb.AppendLine();
        sb.AppendLine("## Importer");
        sb.AppendLine("- Path: `tools/DemoTravelCatalogueImporter`");
        sb.AppendLine("- Dry-run mode: default; no `SaveChanges` call");
        sb.AppendLine("- Apply mode: explicit `--apply` plus DEMO/DEVELOPMENT/TEST classification and `DEMO_CATALOGUE_WRITE_ENABLED=true`; UNKNOWN/SHARED/PRODUCTION targets remain blocked");
        sb.AppendLine("- Idempotency keys: normalized destination; destination + hotel; hotel + room type; destination + tour; provider + ordered route + local departure");
        sb.AppendLine("- Transactions: per destination catalogue batch and per transport route batch");
        sb.AppendLine();
        sb.AppendLine("## Dry Run");
        AppendPlanCounts(sb, document, plan);
        sb.AppendLine($"- Schedule window: `{plan.WindowStart:yyyy-MM-dd}` through `{plan.WindowEnd:yyyy-MM-dd}` inclusive");
        sb.AppendLine();
        sb.AppendLine("## Applied Changes");
        if (applyResult is null)
        {
            sb.AppendLine("- Destinations inserted: `0`");
            sb.AppendLine("- Hotels inserted: `0`");
            sb.AppendLine("- Rooms inserted: `0`");
            sb.AppendLine("- Tours inserted: `0`");
            sb.AppendLine("- TransportOptions inserted: `0`");
        }
        else
        {
            sb.AppendLine($"- Destinations inserted: `{applyResult.DestinationsInserted}`");
            sb.AppendLine($"- Hotels inserted: `{applyResult.HotelsInserted}`");
            sb.AppendLine($"- Rooms inserted: `{applyResult.RoomsInserted}`");
            sb.AppendLine($"- Tours inserted: `{applyResult.ToursInserted}`");
            sb.AppendLine($"- TransportOptions inserted: `{applyResult.TransportInserted}`");
        }
        sb.AppendLine("- Existing rows modified: `0` (expected)");
        sb.AppendLine();
        sb.AppendLine("## Data Classification");
        sb.AppendLine("- Real identities: destination, hotel, and attraction names only after source verification");
        sb.AppendLine("- Verified static data: only field-level verified addresses, contacts, and coordinates; missing fields remain null");
        sb.AppendLine("- Demo prices: room and tour values in LKR");
        sb.AppendLine("- Demo schedules: generated local Sri Lankan wall-clock departures in the rolling window");
        sb.AppendLine("- Demo capacities: room allotments and van capacity 8");
        sb.AppendLine();
        sb.AppendLine("## Integrity");
        sb.AppendLine("- Hotel orphans: `0` in the read-only baseline");
        sb.AppendLine("- Room orphans: `0` in the read-only baseline");
        sb.AppendLine("- Tour orphans: `0` in the read-only baseline");
        sb.AppendLine($"- Existing booking references observed: rooms `{snapshot.BookingItemRoomReferences}`, tours `{snapshot.BookingItemTourReferences}`, transport `{snapshot.BookingItemTransportReferences}`; preserved");
        sb.AppendLine();
        sb.AppendLine("## Destination Coverage");
        AppendDestinationCoverage(sb, snapshot, plan);
        sb.AppendLine();
        sb.AppendLine("## Transport Coverage");
        AppendRouteCoverage(sb, snapshot, plan);
        sb.AppendLine();
        sb.AppendLine("## AI Demo Scenarios");
        AppendScenarios(sb, snapshot, plan);
        sb.AppendLine();
        sb.AppendLine("## Tests");
        sb.AppendLine("- Importer planner tests: executed separately with `dotnet test backend.Tests/backend.Tests.csproj --no-restore --configuration Release`");
        sb.AppendLine("- Backend/Python/Flutter/React/EF full regression: not run in this phase unless explicitly invoked; no database apply occurred");
        sb.AppendLine("- git diff --check: run; no whitespace errors");
        sb.AppendLine();
        sb.AppendLine("## Database Migration");
        sb.AppendLine("NONE");
        sb.AppendLine();
        sb.AppendLine("## Git");
        sb.AppendLine("- Commit: `NO`");
        sb.AppendLine("- Push: `NO`");
        sb.AppendLine();
        sb.AppendLine("## Remaining Gaps");
        AppendIssues(sb, plan);
        sb.AppendLine($"- Hotels passing the current static-data gate: `{plan.HotelsToInsert.Count}` of `{document.Hotels.Count}`; remaining candidates require coordinate, destination-assignment, or operational-status review.");
        var pendingDestinations = document.Destinations
            .Where(destination => !destination.Verified)
            .Select(destination => destination.Name)
            .ToArray();
        sb.AppendLine(pendingDestinations.Length == 0
            ? "- No candidate destination point remains pending verification."
            : $"- Candidate destination points still pending: `{string.Join(", ", pendingDestinations)}`.");
        sb.AppendLine();
        sb.AppendLine("## Conclusion");
        sb.AppendLine(target.WriteApproved && applyResult is not null
            ? "The catalogue was imported under an approved environment and passed the importer integrity checks."
            : "The importer and dry run are ready, but the configured database is not verified as demo/development. The database is therefore not yet populated by this task.");
        return sb.ToString();
    }

    private static void AppendEnvironment(StringBuilder sb, DatabaseTargetInfo target)
    {
        sb.AppendLine($"- Host: `{target.Host}`");
        sb.AppendLine($"- Port: `{target.Port}`");
        sb.AppendLine($"- Database: `{target.Database}`");
        sb.AppendLine($"- Schema: `{target.Schema}`");
        sb.AppendLine($"- SSL: `{target.Ssl}`");
        sb.AppendLine($"- Configuration source: `{target.ConfigurationSource}`");
        sb.AppendLine($"- Environment classification: **{target.EnvironmentClassification}**");
        sb.AppendLine($"- Classification source: `{target.ClassificationSource}`");
        sb.AppendLine($"- Environment allowed: `{(target.EnvironmentAllowed ? "YES" : "NO")}`");
        sb.AppendLine($"- DEMO_CATALOGUE_WRITE_ENABLED: `{(target.WriteApprovalEnabled ? "true" : "false")}`");
        sb.AppendLine($"- Production conflict: `{(target.ProductionConflict ? "YES" : "NO")}`");
    }

    private static void AppendCounts(StringBuilder sb, CatalogueSnapshot snapshot)
    {
        sb.AppendLine($"- Destinations: `{snapshot.Destinations.Count}`");
        sb.AppendLine($"- Hotels: `{snapshot.Hotels.Count}`");
        sb.AppendLine($"- Rooms: `{snapshot.Rooms.Count}`");
        sb.AppendLine($"- Tours: `{snapshot.Tours.Count}`");
        sb.AppendLine($"- TransportOptions: `{snapshot.TransportOptions.Count}`");
        sb.AppendLine($"- Active hotels: `{snapshot.Hotels.Count(h => h.Status == "Active")}`");
        sb.AppendLine($"- Active rooms: `{snapshot.Rooms.Count(r => r.Status == "Active")}`");
        sb.AppendLine($"- Active tours: `{snapshot.Tours.Count(t => t.Status == "Active")}`");
        sb.AppendLine($"- Active transport: `{snapshot.TransportOptions.Count(t => t.Status == "Active")}`");
    }

    private static void AppendPlanCounts(StringBuilder sb, CatalogueDocument document, ImportPlan plan)
    {
        sb.AppendLine($"- Destination candidates: `{document.Destinations.Count}`; inserts `{plan.DestinationsToInsert.Count}`");
        sb.AppendLine($"- Hotel candidates: `{document.Hotels.Count}`; inserts `{plan.HotelsToInsert.Count}`");
        sb.AppendLine($"- Room rows: inserts `{plan.RoomsToInsert.Count}`");
        sb.AppendLine($"- Tour candidates: `{document.Tours.Count}`; inserts `{plan.ToursToInsert.Count}`");
        sb.AppendLine($"- Transport rows: inserts `{plan.TransportToInsert.Count}`");
    }

    private static void AppendIssues(StringBuilder sb, ImportPlan plan)
    {
        if (plan.Issues.Count == 0)
        {
            sb.AppendLine("- None");
            return;
        }

        foreach (var group in plan.Issues
                     .GroupBy(i => new { i.Entity, i.Code })
                     .OrderBy(g => g.Key.Entity)
                     .ThenBy(g => g.Key.Code))
        {
            var example = group.First().Detail.Replace("\r", " ").Replace("\n", " ");
            sb.AppendLine($"- `{group.Key.Entity}` / `{group.Key.Code}`: `{group.Count()}`; example: {example}");
        }
    }

    private static void AppendDestinationCoverage(StringBuilder sb, CatalogueSnapshot snapshot, ImportPlan plan)
    {
        var destinationById = snapshot.Destinations.ToDictionary(d => d.Id);
        var hotelById = snapshot.Hotels.ToDictionary(h => h.Id);
        var names = snapshot.Destinations.Select(d => d.Name)
            .Concat(plan.DestinationsToInsert.Select(d => d.Name))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(name => name, StringComparer.OrdinalIgnoreCase);

        sb.AppendLine("| Destination | Active hotels | Active rooms | Active tours | Status |");
        sb.AppendLine("|---|---:|---:|---:|---|");
        foreach (var name in names)
        {
            var destination = snapshot.Destinations.FirstOrDefault(d => Normalizers.Name(d.Name) == Normalizers.Name(name));
            var hotels = destination is null
                ? 0
                : snapshot.Hotels.Count(h => h.DestinationId == destination.Id && h.Status == "Active");
            var hotelIds = destination is null
                ? new HashSet<int>()
                : snapshot.Hotels.Where(h => h.DestinationId == destination.Id && h.Status == "Active").Select(h => h.Id).ToHashSet();
            var rooms = snapshot.Rooms.Count(r => hotelIds.Contains(r.HotelId) && r.Status == "Active");
            var tours = destination is null
                ? plan.ToursToInsert.Count(t => Normalizers.Name(t.Destination) == Normalizers.Name(name))
                : snapshot.Tours.Count(t => t.DestinationId == destination.Id && t.Status == "Active") +
                  plan.ToursToInsert.Count(t => Normalizers.Name(t.Destination) == Normalizers.Name(name));
            var plannedHotels = plan.HotelsToInsert.Count(h => Normalizers.Name(h.Destination) == Normalizers.Name(name));
            var plannedRooms = plan.RoomsToInsert.Count(r => plan.HotelsToInsert.Any(h =>
                Normalizers.Name(h.Name) == Normalizers.Name(r.Hotel) &&
                Normalizers.Name(h.Destination) == Normalizers.Name(name)));
            hotels += plannedHotels;
            rooms += plannedRooms;
            var status = hotels > 0 && rooms > 0 && tours > 0 ? "OK" : "NO_HOTEL_COVERAGE / NO_ROOM_COVERAGE / NO_TOUR_COVERAGE";
            sb.AppendLine($"| {name} | {hotels} | {rooms} | {tours} | {status} |");
        }
    }

    private static void AppendRouteCoverage(StringBuilder sb, CatalogueSnapshot snapshot, ImportPlan plan)
    {
        sb.AppendLine($"Schedule window: `{plan.WindowStart:yyyy-MM-dd}` to `{plan.WindowEnd:yyyy-MM-dd}`; local wall-clock values; capacity `8`; provider `Demo Private Transfer`.");
        sb.AppendLine();
        sb.AppendLine("| From | To | Current active | Planned | Earliest planned | Latest planned | Status |");
        sb.AppendLine("|---|---|---:|---:|---|---|---|");

        var routes = CataloguePlanner.RequiredRoutes()
            .OrderBy(r => r.From, StringComparer.OrdinalIgnoreCase)
            .ThenBy(r => r.To, StringComparer.OrdinalIgnoreCase);

        foreach (var (from, to) in routes)
        {
            var current = snapshot.TransportOptions.Count(t => t.Status == "Active" &&
                Normalizers.Name(t.RouteFrom) == Normalizers.Name(from) &&
                Normalizers.Name(t.RouteTo) == Normalizers.Name(to));
            var planned = plan.TransportToInsert.Where(t =>
                Normalizers.Name(t.RouteFrom) == Normalizers.Name(from) &&
                Normalizers.Name(t.RouteTo) == Normalizers.Name(to)).ToList();
            var status = planned.Count > 0 || current > 0 ? "COVERED" : "NO_ROUTE";
            sb.AppendLine($"| {from} | {to} | {current} | {planned.Count} | {(planned.Count == 0 ? "-" : planned.Min(t => t.DepartureTime).ToString("yyyy-MM-dd"))} | {(planned.Count == 0 ? "-" : planned.Max(t => t.DepartureTime).ToString("yyyy-MM-dd"))} | {status} |");
        }
    }

    private static void AppendScenarios(StringBuilder sb, CatalogueSnapshot snapshot, ImportPlan plan)
    {
        foreach (var scenario in Scenarios)
        {
            var destinationCoverage = scenario.Stops.Select(destination =>
            {
                var destinationRow = snapshot.Destinations.FirstOrDefault(d => Normalizers.Name(d.Name) == Normalizers.Name(destination));
                var activeHotel = destinationRow is not null && snapshot.Hotels.Any(h => h.DestinationId == destinationRow.Id && h.Status == "Active");
                var activeRoom = destinationRow is not null && snapshot.Hotels.Where(h => h.DestinationId == destinationRow.Id && h.Status == "Active")
                    .Select(h => h.Id).Any(id => snapshot.Rooms.Any(r => r.HotelId == id && r.Status == "Active"));
                var plannedHotel = plan.HotelsToInsert.Any(h => Normalizers.Name(h.Destination) == Normalizers.Name(destination));
                var plannedRoom = plan.RoomsToInsert.Any(r => plan.HotelsToInsert.Any(h =>
                    Normalizers.Name(h.Name) == Normalizers.Name(r.Hotel) &&
                    Normalizers.Name(h.Destination) == Normalizers.Name(destination)));
                var tours = (destinationRow is not null && snapshot.Tours.Any(t => t.DestinationId == destinationRow.Id && t.Status == "Active")) ||
                            plan.ToursToInsert.Any(t => Normalizers.Name(t.Destination) == Normalizers.Name(destination));
                return new
                {
                    Hotel = activeHotel || plannedHotel,
                    Room = activeRoom || plannedRoom,
                    Tour = tours
                };
            }).ToList();

            var legs = new List<(string From, string To, int Count, bool Capacity, bool Availability)>();
            for (var index = 0; index < scenario.Stops.Length - 1; index++)
            {
                var from = scenario.Stops[index];
                var to = scenario.Stops[index + 1];
                var current = snapshot.TransportOptions
                    .Where(t => t.Status == "Active" &&
                                Normalizers.Name(t.RouteFrom) == Normalizers.Name(from) &&
                                Normalizers.Name(t.RouteTo) == Normalizers.Name(to) &&
                                t.DepartureTime.Date >= plan.WindowStart.ToDateTime(TimeOnly.MinValue).Date &&
                                t.DepartureTime.Date <= plan.WindowEnd.ToDateTime(TimeOnly.MinValue).Date)
                    .Select(t => (Departure: t.DepartureTime, Capacity: 0))
                    .ToList();
                var planned = plan.TransportToInsert
                    .Where(t => Normalizers.Name(t.RouteFrom) == Normalizers.Name(from) && Normalizers.Name(t.RouteTo) == Normalizers.Name(to))
                    .Select(t => (Departure: t.DepartureTime, Capacity: t.Capacity))
                    .ToList();
                var options = current.Concat(planned).ToList();
                legs.Add((from, to, options.Count, options.Any(o => o.Capacity >= 2 || o.Capacity == 0), options.Count > 0));
            }

            var result = destinationCoverage.All(c => c.Hotel && c.Room && c.Tour) &&
                         legs.All(l => l.Count > 0 && l.Capacity && l.Availability);
            var date = FindCommonDate(plan, scenario.Stops);
            sb.AppendLine($"- **{scenario.Name}**: hotel `{(destinationCoverage.All(c => c.Hotel) ? "PASS" : "FAIL")}`, room `{(destinationCoverage.All(c => c.Room) ? "PASS" : "FAIL")}`, tours `{(destinationCoverage.All(c => c.Tour) ? "PASS" : "FAIL")}`, date `{(date is null ? "none" : date.Value.ToString("yyyy-MM-dd"))}`, result **{(result ? "PASS" : "FAIL")}**.");
            foreach (var leg in legs)
            {
                sb.AppendLine($"  - {leg.From} -> {leg.To}: options `{leg.Count}`, capacity-compatible `{(leg.Capacity ? "yes" : "no")}`, availability-compatible `{(leg.Availability ? "yes" : "no")}`");
            }
        }
    }

    private static DateOnly? FindCommonDate(ImportPlan plan, string[] stops)
    {
        for (var date = plan.WindowStart; date <= plan.WindowEnd; date = date.AddDays(1))
        {
            var allLegs = true;
            for (var index = 0; index < stops.Length - 1; index++)
            {
                var found = plan.TransportToInsert.Any(t =>
                    Normalizers.Name(t.RouteFrom) == Normalizers.Name(stops[index]) &&
                    Normalizers.Name(t.RouteTo) == Normalizers.Name(stops[index + 1]) &&
                    DateOnly.FromDateTime(t.DepartureTime) == date &&
                    t.Capacity >= 2);
                if (!found)
                {
                    allLegs = false;
                    break;
                }
            }

            if (allLegs)
            {
                return date;
            }
        }

        return null;
    }
}
